name: Documentation issue
description: Report incorrect, unclear, or outdated documentation
title: "[Docs]: "
labels:
  - documentation
body:
  - type: input
    id: location
    attributes:
      label: Where is the problem?
      description: File, section, or URL
      placeholder: README.md -> Install
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What is wrong or unclear?
      placeholder: The quick start skips `cmdry i`, so first-time users may fail.
    validations:
      required: true

  - type: textarea
    id: fix
    attributes:
      label: Suggested correction
      placeholder: Add `cmdry i` to the first-run flow.

  - type: textarea
    id: context
    attributes:
      label: Extra context
      description: Screenshots, command output, or links if helpful.
