name: UX / CLI feedback
description: Report confusing output, friction, or rough edges in the Commandry user experience
title: "[UX]: "
labels:
  - ux
body:
  - type: textarea
    id: friction
    attributes:
      label: What felt confusing or slow?
      description: Describe the specific command, screen, or workflow that caused friction.
      placeholder: The setup flow was unclear because...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: What were you trying to do?
      description: Share the user goal, not just the command.
      placeholder: I was trying to export a runbook after...
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current experience
      description: Paste the relevant output or describe what Commandry showed.
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What would have felt better?
      placeholder: A shorter hint, a clearer status line, a different command name...
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS + shell
      placeholder: Windows 11 + PowerShell 7
